# Generated by Django 3.1.4 on 2020-12-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticValues',
            fields=[
                ('updateTime', models.CharField(default='2020.11.21', max_length=15, primary_key=True, serialize=False)),
                ('TotalCase', models.TextField(default='0')),
                ('TotalDeath', models.TextField(default='0')),
                ('TotalRecovered', models.TextField(default='0')),
                ('NowCase', models.TextField(default='0')),
                ('TotalChecking', models.TextField(default='0')),
                ('TodayCase', models.TextField(default='0')),
                ('TodayRecovered', models.TextField(default='0')),
            ],
        ),
    ]
